name: Sample App Tests

on: push

jobs:
  sample_app_tests: 
    # Indentation de 2 espaces pour les paramètres du job
    name: "Run Tests Using Jest" 
    runs-on: ubuntu-latest # Assurez-vous que c'est bien 2 espaces ici et que ce n'est PAS une tabulation.
    steps: 
      # Indentation de 4 espaces pour les éléments de la liste 'steps'
      - uses: actions/checkout@v3 
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies 
        working-directory: td5/scripts/sample-app 
        run: npm install 
      - name: Run tests 
        working-directory: td5/scripts/sample-app 
        run: npm test