# .github/workflows/app-tests.yml (Version Optimisée)
name: Sample App Tests

on: push

jobs:
  sample_app_tests: 
    name: "Run Tests Using Jest" 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v3 
      
      - name: ⚙️ Install dependencies and Run tests
        # Applique le working-directory à TOUTES les commandes 'run' de cette étape
        working-directory: td5/scripts/sample-app 
        run: |
          npm install
          npm test